language: cpp
dist: trusty
sudo: true
before_install: 
 - sudo apt-get update
 - sudo apt-get install -yq software-properties-common
 - sudo add-apt-repository "deb http://us-central1.gce.clouds.archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
 - sudo add-apt-repository -y ppa:radio-astro/main
 - sudo apt-get update
 - sudo apt-get install -qy cmake libblitz0-dev python-dev libcasacore2-dev libblas-dev liblapack-dev libgdbm-dev wcslib-dev libfftw3-dev python-numpy libcfitsio3-dev casarest libboost-thread-dev libboost-system-dev
install: 
 - cd ${TRAVIS_BUILD_DIR}
 - mkdir build && cd build
 - cmake ..
 - make
script: 
 - true
